### ISSUE TITLE
Physics based animations

### ISSUE THREAD

**Issue by souporserious** [react-tools/react-move#33]
### Problem or feature description
First, just wanted to say what a wonderful library this is and thank you for making it! I'm coming from using animated and react-motion and have read the comparison, but was curious if there are any plans for physics based animations? Would it possible to allow other libraries like [wobble](https://github.com/skevy/wobble) to be plugged in? I'd be willing to help with whatever and submit a PR, please let me know.

**Comment by tannerlinsley** [comment]
Have you tried using https://GitHub.com/TannerLinsley/Springer? It can
achieve a physics-based-like animation in time based animation
environments. The actual technical difference between time based and
physics based animation logic is the way the system handles interruption.

**Comment by souporserious** [comment]
Yes I have :) sorry, I should have mentioned that. I'd like to be able to have better interruptible animations. Is there any way to do have both options in react-move or would it take too much rearchitecting?

**Comment by tannerlinsley** [comment]
That's a question for @sghall

**Comment by sghall** [comment]
@souporserious I think it would be great to support these types of animations.  It would require some work, but I believe it's possible we could make some tweaks and support both styles. If you want to do a little leg work on this, that would be awesome.  Would definitely would welcome a PR. 

Off the top of my head. I think for physics based animations (you may actually know better than I do) you really want to stop ticking when some criteria is met (e.g. the value has reached the goal value or velocity === 0) rather than a specific elapsed time.

Looks like wobble, for example, does a check like this:
https://github.com/skevy/wobble/blob/develop/src/index.js#L390

And is called here:
https://github.com/skevy/wobble/blob/develop/src/index.js#L364

(I just took a quick look so take this with a grain of salt)

In react-move checking is done here:
https://github.com/react-tools/react-move/blob/master/src/core/transition/schedule.js#L124

Not sure what all would be involved from there, but seems like it would be possible.  Need to consider interrupts carefully I suppose.

Be interested to see what you come up with.

**Comment by souporserious** [comment]
Awesome, sounds good! I only know a little bit about how it works, but I'm up for the challenge. I'll work on a PR as soon as I get some time. Thanks for the info!

**Comment by sghall** [comment]
@souporserious did you have a chance to get into this?  Was wondering of this seemed viable after actually exploring it.

**Comment by souporserious** [comment]
I have not unfortunately 😞
