### ISSUE TITLE
Force update animation

### ISSUE THREAD

**Issue by markov00** [react-tools/react-move#42]
### Problem or feature description
I've started using this library for animate svg chart elements (a scatterplot) and it's great. 
I now have the case that I need to animate my chart either when data change (and this is the standard working behaviour) and either when my chart size change (this is what I cannot find a good way for that).
As in your example `Simple Bars`, you pass the original data array on a `NodeGroup`, than using d3 scales you change the width and x position for each transition event. If you update data, that this will trigger a change in the animation. The problem is that I don't see a way to update my scale ranges with the new width/height of the chart and trigger a rendering (animated or not).

Last fact: I can't use viewBox to fix this because I can't/ don't want to scale text, line sizes etc. 

### Versions (only needed for problems)

- React-Move: 2.7.0
- React: 16.4.2
- Browser: Chrome 68 OSX

**Comment by sghall** [comment]
Hey, yeah, totally doable.  

React-move is listening for your data to change:

https://github.com/react-tools/react-move/blob/999927532ca5be90fc8a54656c41fa2d9b8848eb/src/NodeGroup/NodeGroup.js#L58

So just send a new data array with the new layout when you want to update.  For what you're trying to do, I wouldn't use the scales directly in NodeGroup component like the example. Do all the calculation outside and pass it in.   If the data values change update your array...if the browser size changes update your array.

**Comment by markov00** [comment]
Ok, but what about animate an svg path?
Can I animate directly the `d` attribute passing a new, precomputed `d` path?

**Comment by sghall** [comment]
Sure. Absolutely.  The value you are interpolating just gets handed off to [d3-interpolate](https://github.com/d3/d3-interpolate).

If the name of your key is "transform" it is interpolated as an SVG tranform:
https://github.com/d3/d3-interpolate#interpolateTransformSvg

Otherwise it goes to interpolate:
https://github.com/d3/d3-interpolate#interpolate

So if your value is a string path it will get interpolated by:
https://github.com/d3/d3-interpolate/blob/master/README.md#interpolateString

Which looks for number inside strings and interpolates them.

**Comment by markov00** [comment]
Great thanks for the info.
